<a href="https://colab.research.google.com/github/CASV2001/gitprueba/blob/master/ProyectoMate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Comandos y ayudas

In [ ]:
import numpy as np


print("- Matriz creada con una lista de listas:")
MatrizA = np.matrix([ [1  ,-4, 3], [12 , 3, 5] , [7.2, 5, 0] , [1,1,1]])
MatrizB = np.matrix([[1, 0, 5], [4, 3 , 9], [2, 5 ,1] , [0,0,0]])
MatrizC = MatrizA - MatrizB
print(MatrizC)


"""Invertir matricez"""
"""print(np.linalg.inv(MatrizC))"""

N = input("Ingresa un numero")
n = int(N)
print("- Matriz creada con np.zeros:")
dimensiones=(3,3)
matriz_ceros = np.zeros(dimensiones)
print(matriz_ceros)


print("Matriz Identidad nxn")

Filas, columnas = MatrizA.shape

dimensiones = (Filas, columnas)

MatrizD = np.zeros(dimensiones)

print(MatrizD)

MatrizI = np.identity(Filas)

print(MatrizI)


Solución del ejercicio 47 y 48

In [27]:
import numpy as np

MatrizA = np.matrix([[0.293, 0, 0] , [0.014, 0.207, 0.017] , [0.044, 0.010, 0.216 ]])
Exportaciones = np.matrix([[13213], [17597], [1786]])
print("Tenemos nuestra matriz A")
print(MatrizA)
print("Y nuestro vector columna")
print(Exportaciones)

Filas, columnas = MatrizA.shape

MatrizI = np.identity(Filas)

MatrizResta = MatrizI - MatrizA
print("Restamos a la matriz A la matriz Identidad")
print(MatrizResta)

MatrizRI = np.linalg.inv(MatrizResta)
print("Le sacamos Inversa")
print(MatrizRI)

MatrizResultado = MatrizRI*Exportaciones
print("Lo multiplicamos por e vector columna lo que nos da el resultado final")

print(MatrizResultado)


Tenemos nuestra matriz A
[[0.293 0.    0.   ]
 [0.014 0.207 0.017]
 [0.044 0.01  0.216]]
Y nuestro vector columna
[[13213]
 [17597]
 [ 1786]]
Restamos a la matriz A la matriz Identidad
[[ 0.707  0.     0.   ]
 [-0.014  0.793 -0.017]
 [-0.044 -0.01   0.784]]
Le sacamos Inversa
[[1.41442716 0.         0.        ]
 [0.02668001 1.26137896 0.02735133]
 [0.07972142 0.01608902 1.27585907]]
Lo multiplicamos por e vector columna lo que nos da el resultado final
[[18688.82602546]
 [22597.85790232]
 [ 3615.16189304]]


Solución para un modelo de economía con N sectores